### ISSUE TITLE
將交叉分析篩選器同步至其他頁面上使用

### ISSUE THREAD

**Issue by myyt0523** [MicrosoftDocs/powerbi-docs.zh-tw#15]
請問此交叉分析篩選器同步功能在儀表板上是否能使用?
我在power bi desktop使用此功能確實能同步, 但於power BI服務釘選在儀錶板後,此同步功能失效了

---
#### 文件詳細資料

⚠ *請勿編輯此區段。 這是 docs.microsoft.com ➟ GitHub 問題連結的必要項。*

* ID: 2f177d47-9600-eab6-a282-09d40d5c2dff
* Version Independent ID: 792909b9-e2fa-8a31-1da9-2223307e799d
* Content: [Power BI 中的交叉分析篩選器 - Power BI](https://docs.microsoft.com/zh-tw/power-bi/visuals/power-bi-visualization-slicers#feedback)
* Content Source: [powerbi-docs/visuals/power-bi-visualization-slicers.md](https://github.com/MicrosoftDocs/powerbi-docs.zh-tw/blob/live/powerbi-docs/visuals/power-bi-visualization-slicers.md)
* Service: **powerbi**
* Sub-service: **powerbi-desktop**
* GitHub Login: @maggiesMSFT
* Microsoft Alias: **maggies**

**Comment by srvbpigh** [comment]
Hello, @myyt0523
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by srvbpigh** [comment]
您好，@myyt0523，  

非常感謝您的貢獻。您的意見反應與原始文件相關。  

因此，我們會將此問題移轉至英文存放庫。請由此處查看問題狀態 - https://github.com/MicrosoftDocs/powerbi-docs/issues/2088。  

我們由衷感謝您對文章的貢獻。   

順頌時祺  
Microsoft DOCS 國際小組
